-- MySQL Script generated by MySQL Workbench
-- Sat May 16 13:59:52 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mygiftday
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mygiftday` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mygiftday` ;

-- -----------------------------------------------------
-- Table `mygiftday`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mygiftday`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `id_facebook` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `birthday` DATETIME NULL,
  `status` TINYINT NOT NULL,
  `update` TIMESTAMP NULL,
  `register_date` TIMESTAMP NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mygiftday`.`event_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mygiftday`.`event_type` (
  `id_event_type` INT NOT NULL AUTO_INCREMENT,
  `event_type` VARCHAR(45) NULL,
  `status` TINYINT NOT NULL,
  `update` TIMESTAMP NULL,
  `register_date` TIMESTAMP NULL,
  PRIMARY KEY (`id_event_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mygiftday`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mygiftday`.`provider` (
  `id_provider` INT NOT NULL AUTO_INCREMENT,
  `provider` TEXT NULL,
  `status` TINYINT NOT NULL,
  `register_date` TIMESTAMP NULL,
  `update` TIMESTAMP NULL,
  PRIMARY KEY (`id_provider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mygiftday`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mygiftday`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `id_provider` INT NOT NULL,
  `product` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `picture` TEXT NULL,
  `status` TINYINT NOT NULL,
  `register_date` TIMESTAMP NULL,
  `update` TIMESTAMP NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_product_provider1_idx` (`id_provider` ASC),
  CONSTRAINT `fk_product_provider1`
    FOREIGN KEY (`id_provider`)
    REFERENCES `mygiftday`.`provider` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mygiftday`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mygiftday`.`event` (
  `id_event` INT NOT NULL AUTO_INCREMENT,
  `id_event_type` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_product` INT NULL,
  `url` VARCHAR(45) NULL,
  `iwant` TEXT NULL,
  `date` VARCHAR(45) NULL,
  `amount` DOUBLE NULL,
  `value_product` DOUBLE NULL,
  `first_amount` DOUBLE NULL,
  `last_date` DATETIME NULL,
  `status` TINYINT NOT NULL,
  `register_date` TIMESTAMP NULL,
  `update` TIMESTAMP NULL,
  PRIMARY KEY (`id_event`),
  INDEX `fk_event_event_type_idx` (`id_event_type` ASC),
  INDEX `fk_event_user1_idx` (`id_user` ASC),
  INDEX `fk_event_product1_idx` (`id_product` ASC),
  CONSTRAINT `fk_event_event_type`
    FOREIGN KEY (`id_event_type`)
    REFERENCES `mygiftday`.`event_type` (`id_event_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mygiftday`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_product1`
    FOREIGN KEY (`id_product`)
    REFERENCES `mygiftday`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mygiftday`.`bonus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mygiftday`.`bonus` (
  `id_bonus` INT NOT NULL AUTO_INCREMENT,
  `percentage` DOUBLE NULL,
  `amount` DOUBLE NULL,
  `status` TINYINT NOT NULL,
  `register_date` TIMESTAMP NULL,
  `update` TIMESTAMP NULL,
  PRIMARY KEY (`id_bonus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mygiftday`.`contribution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mygiftday`.`contribution` (
  `id_contribution` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_event` INT NOT NULL,
  `id_bonus` INT NOT NULL,
  `message` DOUBLE NULL,
  `date` DATETIME NULL,
  `status` TINYINT NOT NULL,
  `register_date` TIMESTAMP NULL,
  `update` TIMESTAMP NULL,
  PRIMARY KEY (`id_contribution`),
  INDEX `fk_contributor_user1_idx` (`id_user` ASC),
  INDEX `fk_contributor_event1_idx` (`id_event` ASC),
  INDEX `fk_contributor_bonus1_idx` (`id_bonus` ASC),
  CONSTRAINT `fk_contributor_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mygiftday`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contributor_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mygiftday`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contributor_bonus1`
    FOREIGN KEY (`id_bonus`)
    REFERENCES `mygiftday`.`bonus` (`id_bonus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
